#!/bin/bash
# We always launch munin-html.
# It is a noop if html_strategy is &quot;cgi&quot;
nice /usr/share/munin/munin-html $@ || exit 1

# The result of munin-html is needed for munin-graph.
# It is a noop if graph_strategy is &quot;cgi&quot;
nice /usr/share/munin/munin-graph --cron $@ || exit 1

